services:
  - type: web
    name: sons-sabores-ingressos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: BASE_URL
        value: https://borogodo-sons-sabores-ingressos.onrender.com



      - key: SECRET_KEY
        sync: false
      - key: BASE_URL
        sync: false

      - key: DATABASE_URL
        sync: false

      # ✅ storage temporário (Linux)
      - key: STORAGE_DIR
        value: /tmp/sons_sabores_ingressos_storage

      # FTP
      - key: FTP_HOSTS
        value: br52.hostgator.com.br
      - key: FTP_PORT
        value: "21"
      - key: FTP_PASSIVE
        value: "1"
      - key: FTP_SECURITY
        value: explicit
      - key: FTP_USERNAME
        sync: false
      - key: FTP_PASSWORD
        sync: false
      - key: FTP_DIR
        value: /public_html/borogodobar.com.br/sons_sabores_ingressos_data/
      - key: FTP_PUBLIC_BASE
        value: https://borogodobar.com.br/sons_sabores_ingressos_data
